# Generated by Django 6.0.3 on 2026-05-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_semester',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
